development:
  adapter: mysql2
  encoding: utf8
  database: blog_rails_2
  username: root
  password: 
  host: 127.0.0.1
  port: 3306
  
production:
  adapter: mysql2
  encoding: utf8
  database: blog_rails_2
  username: root
  password: 
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: blog_rails_test
  username: root
  password: 
  host: 127.0.0.1
  port: 3306
